"use client";

import { useState, useEffect } from "react";
import Code from "@/components/ui/Code";
import Graph from "@/components/charts/graph";
import { getIP } from "webrtc-ip";

const webrtc_code = `import { getIP, prefetchIP } from "webrtc-ip";

prefetchIP();

getIP().then((my_ip) => {
    console.log(my_ip);
});`;

const fetch_code = `fetch('https://api.ipify.org')
  .then(response => {
    if (!response.ok) {
      throw new Error('Request failed');
    }
    return response.text();
  })
  .then(data => {
    console.log(data);
  })
  .catch(error => {
    console.error(error);
  });`;

// hard coded syntax highlighting generated by shiki
const webrtc_html: string = `<pre class="text-sm py-8 px-6 rounded-lg !bg-[#0A0A0C] border-[#1F2025] border" style="background-color:#0A0A0C;color:#babed8" tabindex="0"><code><span class="line"><span style="color:#89DDFF;font-style:italic">import</span><span style="color:#89DDFF"> {</span><span style="color:#BABED8"> getIP, prefetchIP</span><span style="color:#89DDFF"> }</span><span style="color:#89DDFF;font-style:italic"> from</span><span style="color:#89DDFF"> "</span><span style="color:#D8FF4A">webrtc-ip</span><span style="color:#89DDFF">"</span><span style="color:#89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D8FF4A">prefetchIP</span><span style="color:#BABED8">()</span><span style="color:#89DDFF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D8FF4A">getIP</span><span style="color:#BABED8">()</span><span style="color:#89DDFF">.</span><span style="color:#D8FF4A">then</span><span style="color:#BABED8">(</span><span style="color:#89DDFF">(</span><span style="color:#BABED8;font-style:italic">my_ip</span><span style="color:#89DDFF">)</span><span style="color:#C792EA"> =></span><span style="color:#89DDFF"> {</span></span>
<span class="line"><span style="color:#BABED8">    console</span><span style="color:#89DDFF">.</span><span style="color:#D8FF4A">log</span><span style="color:#F07178">(</span><span style="color:#BABED8">my_ip</span><span style="color:#F07178">)</span><span style="color:#89DDFF">;</span></span>
<span class="line"><span style="color:#89DDFF">}</span><span style="color:#BABED8">)</span><span style="color:#89DDFF">;</span></span></code></pre>` satisfies TrustedHTML;

const fetch_html: string = `<pre class="text-sm py-8 px-6 rounded-lg !bg-[#0A0A0C] border-[#1F2025] border" style="background-color:#0A0A0C;color:#babed8" tabindex="0"><code><span class="line"><span style="color:#82AAFF">fetch</span><span style="color:#BABED8">(</span><span style="color:#89DDFF">'</span><span style="color:#C3E88D">https://api.ipify.org</span><span style="color:#89DDFF">'</span><span style="color:#BABED8">)</span></span>
<span class="line"><span style="color:#89DDFF">  .</span><span style="color:#82AAFF">then</span><span style="color:#BABED8">(</span><span style="color:#BABED8;font-style:italic">response</span><span style="color:#C792EA"> =></span><span style="color:#89DDFF"> {</span></span>
<span class="line"><span style="color:#89DDFF;font-style:italic">    if</span><span style="color:#F07178"> (</span><span style="color:#89DDFF">!</span><span style="color:#BABED8">response</span><span style="color:#89DDFF">.</span><span style="color:#BABED8">ok</span><span style="color:#F07178">) </span><span style="color:#89DDFF">{</span></span>
<span class="line"><span style="color:#89DDFF;font-style:italic">      throw</span><span style="color:#89DDFF"> new</span><span style="color:#82AAFF"> Error</span><span style="color:#F07178">(</span><span style="color:#89DDFF">'</span><span style="color:#C3E88D">Request failed</span><span style="color:#89DDFF">'</span><span style="color:#F07178">)</span><span style="color:#89DDFF">;</span></span>
<span class="line"><span style="color:#89DDFF">    }</span></span>
<span class="line"><span style="color:#89DDFF;font-style:italic">    return</span><span style="color:#BABED8"> response</span><span style="color:#89DDFF">.</span><span style="color:#82AAFF">text</span><span style="color:#F07178">()</span><span style="color:#89DDFF">;</span></span>
<span class="line"><span style="color:#89DDFF">  }</span><span style="color:#BABED8">)</span></span>
<span class="line"><span style="color:#89DDFF">  .</span><span style="color:#82AAFF">then</span><span style="color:#BABED8">(</span><span style="color:#BABED8;font-style:italic">data</span><span style="color:#C792EA"> =></span><span style="color:#89DDFF"> {</span></span>
<span class="line"><span style="color:#BABED8">    console</span><span style="color:#89DDFF">.</span><span style="color:#82AAFF">log</span><span style="color:#F07178">(</span><span style="color:#BABED8">data</span><span style="color:#F07178">)</span><span style="color:#89DDFF">;</span></span>
<span class="line"><span style="color:#89DDFF">  }</span><span style="color:#BABED8">)</span></span>
<span class="line"><span style="color:#89DDFF">  .</span><span style="color:#82AAFF">catch</span><span style="color:#BABED8">(</span><span style="color:#BABED8;font-style:italic">error</span><span style="color:#C792EA"> =></span><span style="color:#89DDFF"> {</span></span>
<span class="line"><span style="color:#BABED8">    console</span><span style="color:#89DDFF">.</span><span style="color:#82AAFF">error</span><span style="color:#F07178">(</span><span style="color:#BABED8">error</span><span style="color:#F07178">)</span><span style="color:#89DDFF">;</span></span>
<span class="line"><span style="color:#89DDFF">  }</span><span style="color:#BABED8">)</span><span style="color:#89DDFF">;</span></span></code></pre>` satisfies TrustedHTML;


const Home: React.FC = () => {
    const [isWebRTC, setIsWebRTC] = useState(true);
    const [ip, setIp] = useState<string>("");
    const [data, setData] = useState<{ name: string; time: number }[]>([]);
    const [speedFactor, setSpeedFactor] = useState<number | null>(null);
    const [webrtcMs, setWebrtcMs] = useState<number | null>(null);
    const [copied, setCopied] = useState(false);

    useEffect(() => {
        let startWebrtcTime = performance.now();
        getIP().then((ip) => {
            let endWebrtcTime = performance.now();
            setIp(ip);
            let webrtcTime = endWebrtcTime - startWebrtcTime;
            setWebrtcMs(webrtcTime);

            const fetchLinks = async () => {
                const times = await Promise.all([
                    fetchAndTime('ipify', 'https://api.ipify.org/'),
                    fetchAndTime('ipregistry', 'https://api.ipregistry.co/?key=c4j3vfp0lre55jsw'),
                ]);

                const averageFetchTime = times.reduce((a, b) => a + b, 0) / times.length;
                const speedFactor = averageFetchTime / webrtcTime;

                const combinedData = [
                    { name: "WebRTC-IP", time: webrtcTime },
                    { name: "IPIFY", time: times[0] },
                    { name: "IPRegistry", time: times[1] },
                ].sort((a, b) => a.time - b.time);

                setData(combinedData);
                setSpeedFactor(speedFactor);
            };

            fetchLinks();
        });

    }, []);

    async function fetchAndTime(apiName: string, apiUrl: string): Promise<number> {
        let startTime = performance.now();
        return fetch(apiUrl, { cache: "no-store" })
            .then(() => {
                let endTime = performance.now();
                return endTime - startTime;
            })
            .catch(error => {
                console.error(`Error fetching IP from ${apiName}:`, error);
                return -1;
            });
    }

    const copyInstall = () => {
        navigator.clipboard.writeText("npm install webrtc-ip");
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
    };

    return (
        <main className="relative min-h-screen overflow-x-hidden bg-ink-900 text-bone">
            {/* Atmospheric backdrop */}
            <div aria-hidden className="pointer-events-none fixed inset-0 z-0">
                <div className="absolute inset-0 grid-bg grid-fade-mask" />
                <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-[80vw] h-[60vw] rounded-full"
                     style={{ background: "radial-gradient(closest-side, rgba(216,255,74,0.10), transparent 70%)" }} />
                <div className="absolute bottom-0 right-0 w-[50vw] h-[40vw] rounded-full"
                     style={{ background: "radial-gradient(closest-side, rgba(255,107,61,0.06), transparent 70%)" }} />
                <div className="absolute inset-0 bg-noise opacity-[0.035] mix-blend-overlay" />
            </div>

            {/* Top nav */}
            <header className="relative z-10 mx-auto max-w-7xl px-6 md:px-10 pt-8 flex items-center justify-between animate-fade-in">
                <div className="flex items-center gap-3">
                    <div className="w-7 h-7 rounded-[6px] bg-acid relative">
                        <div className="absolute inset-[3px] rounded-[3px] bg-ink-900 grid place-items-center">
                            <div className="w-1.5 h-1.5 rounded-full bg-acid animate-pulse-dot" />
                        </div>
                    </div>
                    <span className="font-ibm text-[13px] tracking-[0.18em] uppercase text-bone/80">webrtc&middot;ip</span>
                </div>
                <nav className="hidden md:flex items-center gap-8 font-ibm text-[12px] tracking-[0.18em] uppercase text-bone/55">
                    <a href="#benchmark" className="hover:text-bone transition">Benchmark</a>
                    <a href="#install" className="hover:text-bone transition">Install</a>
                    <a href="https://github.com/joeyism/webrtc-ip" target="_blank" rel="noreferrer" className="hover:text-bone transition">GitHub</a>
                    <a href="https://www.npmjs.com/package/webrtc-ip" target="_blank" rel="noreferrer"
                       className="px-3 py-2 border border-bone/20 rounded-full text-bone hover:bg-bone/5 transition">
                        npm ↗
                    </a>
                </nav>
            </header>

            {/* HERO */}
            <section className="relative z-10 mx-auto max-w-7xl px-6 md:px-10 min-h-[calc(100vh-6rem)] flex flex-col justify-center pt-12 pb-20">
                <h1 className="display-serif text-[clamp(3rem,9vw,9.5rem)] leading-[0.92] text-bone animate-fade-up"
                    style={{ animationDelay: "120ms" }}>
                    Your IP, <br />
                    <span className="text-bone/90">resolved</span>{" "}
                    <span className="relative inline-block">
                        <span className="text-acid">pretty fast.</span>
                        <span aria-hidden className="absolute -inset-x-2 -bottom-2 h-[2px] bg-acid/40" />
                    </span>
                </h1>

                <p className="mt-8 max-w-2xl font-ibm text-[15px] leading-[1.7] text-bone/65 animate-fade-up"
                   style={{ animationDelay: "200ms" }}>
                    <span className="text-bone">webrtc-ip</span> webrtc-ip uses the browser’s WebRTC stack to discover your public IP via a STUN request. It avoids a traditional HTTP IP-check endpoint, so there are no API keys, rate limits, or REST response parsing, but it still performs a network round trip to a STUN server.
                </p>

                {/* Stat strip */}
                <div className="mt-14 grid grid-cols-2 md:grid-cols-4 gap-px bg-bone/10 border border-bone/10 rounded-2xl overflow-hidden animate-fade-up"
                     style={{ animationDelay: "280ms" }}>
                    <Stat
                        label="Speedup vs. fetch"
                        value={speedFactor ? `${speedFactor.toFixed(2)}×` : "—"}
                        accent
                    />
                    <Stat
                        label="Your WebRTC latency"
                        value={webrtcMs ? `${webrtcMs.toFixed(1)} ms` : "—"}
                    />
                    <Stat
                        label="Your public IP"
                        value={ip || "resolving…"}
                        mono
                    />
                    <Stat
                        label="Dependencies"
                        value="0"
                    />
                </div>
            </section>

            {/* BENCHMARK PANEL */}
            <section id="benchmark" className="relative z-10 mx-auto max-w-7xl px-6 md:px-10 pb-32">
                <div className="mb-8 animate-fade-up" style={{ animationDelay: "60ms" }}>
                    <div className="eyebrow">§ 01 — Comparison</div>
                </div>

                <div className="panel panel-glow corner-marks animate-fade-up" style={{ animationDelay: "140ms" }}>
                    <span /><span /><span /><span />

                    {/* panel header */}
                    <div className="flex items-center justify-between px-6 md:px-10 py-5 border-b border-bone/[0.07]">
                        <div className="flex items-center gap-2">
                            <div className="w-2.5 h-2.5 rounded-full bg-[#FF5F57]" />
                            <div className="w-2.5 h-2.5 rounded-full bg-[#FEBC2E]" />
                            <div className="w-2.5 h-2.5 rounded-full bg-[#28C840]" />
                            <span className="ml-4 font-ibm text-[11px] tracking-[0.18em] uppercase text-bone/50">
                                live-benchmark.tsx
                            </span>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-[1.05fr_1px_1fr]">
                        {/* LEFT: stat + graph */}
                        <div className="px-6 md:px-10 py-10">
                            <div className="eyebrow">webrtc-ip</div>
                            <div className="mt-2 flex items-baseline gap-3">
                                <span className="stat-num text-[6.5rem] md:text-[8rem] leading-none text-bone">
                                    {speedFactor ? speedFactor.toFixed(2) : "0.00"}
                                </span>
                                <span className="stat-num text-[3rem] md:text-[4rem] leading-none text-acid">×</span>
                            </div>
                            <div className="font-ibm text-[13px] text-bone/55 mt-2 max-w-xs">
                                faster than the average <span className="text-bone">fetch()</span> against
                                public IP providers.
                            </div>

                            <div className="hairline my-8" />

                            <div className="-ml-2">
                                <Graph data={data} />
                            </div>
                        </div>

                        {/* divider */}
                        <div className="hidden lg:block bg-bone/[0.07]" />

                        {/* RIGHT: code */}
                        <div className="px-6 md:px-10 py-10 border-t lg:border-t-0 border-bone/[0.07]">
                            <div className="flex items-center justify-between mb-5">
                                <div className="eyebrow">Implementation</div>
                                <div className="inline-flex p-1 rounded-full border border-bone/10 bg-bone/[0.02]">
                                    <Tab active={isWebRTC} onClick={() => setIsWebRTC(true)}>webrtc-ip</Tab>
                                    <Tab active={!isWebRTC} onClick={() => setIsWebRTC(false)}>fetch</Tab>
                                </div>
                            </div>

                            <div className="text-sm">
                                {isWebRTC ?
                                    <Code code={webrtc_code} html={webrtc_html} /> :
                                    <Code code={fetch_code} html={fetch_html} />
                                }
                            </div>

                        </div>
                    </div>

                    {/* panel footer */}
                    <div className="px-6 md:px-10 py-4 border-t border-bone/[0.07] font-ibm text-[11px] tracking-[0.18em] uppercase text-bone/45">
                        <span>Returned IP &mdash; <span className="text-acid normal-case tracking-normal font-medium">{ip || "—"}</span></span>
                    </div>
                </div>
            </section>

            {/* INSTALL */}
            <section id="install" className="relative z-10 mx-auto max-w-7xl px-6 md:px-10 pb-32">
                <div className="panel px-6 md:px-12 py-12 md:py-16 flex flex-col md:flex-row md:items-center md:justify-between gap-10">
                    <div>
                        <div className="eyebrow">§ 02 — Installation</div>
                        <h2 className="display-serif text-3xl md:text-5xl mt-3 max-w-xl">
                            Simple installation.
                        </h2>
                    </div>

                    <div className="w-full md:w-auto">
                        <button
                            onClick={copyInstall}
                            className="group relative flex items-center justify-between gap-6 px-5 py-4 rounded-lg
                                       bg-ink-900 border border-bone/10 hover:border-acid/50 transition
                                       font-ibm text-sm text-bone min-w-[320px] w-full"
                        >
                            <span className="flex items-center gap-3">
                                <span className="text-acid">$</span>
                                <span>npm install webrtc-ip</span>
                            </span>
                            <span className="text-[11px] tracking-[0.18em] uppercase text-bone/40 group-hover:text-acid transition">
                                {copied ? "copied" : "copy"}
                            </span>
                        </button>
                    </div>
                </div>
            </section>

            <footer className="relative z-10 mx-auto max-w-7xl px-6 md:px-10 py-10 border-t border-bone/10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 font-ibm text-[11px] tracking-[0.18em] uppercase text-bone/40">
                <div>© {new Date().getFullYear()} · joey malvinni</div>
                <div className="flex items-center gap-6">
                    <a href="https://github.com/joeyism/webrtc-ip" target="_blank" rel="noreferrer" className="hover:text-bone transition">Github</a>
                    <a href="https://www.npmjs.com/package/webrtc-ip" target="_blank" rel="noreferrer" className="hover:text-bone transition">npm</a>
                </div>
            </footer>
        </main>
    );
}

const Stat: React.FC<{ label: string; value: string; mono?: boolean; accent?: boolean }> = ({ label, value, mono, accent }) => (
    <div className="bg-ink-800 px-6 py-7">
        <div className="eyebrow mb-3">{label}</div>
        <div className={`${mono ? "font-ibm text-xl md:text-2xl" : "stat-num text-3xl md:text-5xl"} ${accent ? "text-acid" : "text-bone"} leading-none tracking-tight truncate`}>
            {value}
        </div>
    </div>
);

const Tab: React.FC<{ active: boolean; onClick: () => void; children: React.ReactNode }> = ({ active, onClick, children }) => (
    <button
        onClick={onClick}
        className={`px-4 py-1.5 rounded-full font-ibm text-[11px] tracking-[0.18em] uppercase transition ${
            active ? "bg-acid text-ink-900" : "text-bone/55 hover:text-bone"
        }`}
    >
        {children}
    </button>
);

export default Home;
